### ISSUE TITLE
Method 'after' can't attach files to allure report

### ISSUE THREAD

**Issue by merkushevio** [sskorol/ts-test-decorators#10]
Couldn't attach logs after test. I've copied settings from mocha-allure2-example. And if use in after method allure global variable test crushed with message.
Error message:
 "after each" hook for <TestName>
Error: No executable!
 at MochaAllureInterface.get [as currentExecutable] (node_modules/mocha-allure2-reporter/src/MochaAllureInterface.ts:124:13)
 at MochaAllureInterface.attachment (node_modules/mocha-allure2-reporter/src/MochaAllureInterface.ts:88:10)
 at MochaAllureInterface.AllureInterface.createAttachment (node_modules/allure2-js-commons/src/AllureInterface.ts:53:9)

**Comment by sskorol** [comment]
@merkushevio thanks, I'll check it

**Comment by sskorol** [comment]
@merkushevio please try https://www.npmjs.com/package/mocha-allure2-reporter v0.0.3, should be fixed now.

**Comment by merkushevio** [comment]
@sskorol Thanks. All work perfectly.
